name: neura
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  flutter_svg: ^2.2.1
  flutter_bloc: ^9.1.1
  flutter_secure_storage: ^9.2.4
  dio: ^5.9.0
  socket_io_client: ^3.1.2
  another_flushbar: ^1.12.32
  loading_animation_widget: ^1.3.0
  intl: ^0.20.2
  provider: ^6.1.5+1
  firebase_messaging: ^16.0.3
  firebase_core: ^4.2.0
  flutter_local_notifications: ^19.5.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  assets:
    - assets/svg/

  uses-material-design: true


